#!/usr/bin/env python3
"""
reader_questions.py  -  questions to put to the dataset

A long list of questions a reader can pick from, grouped by what they
ask about, for the Questions button on the Ask Claude tab.  They are
here to prompt thought as much as to be used as they stand: pick one,
change the book or the word, and ask.

"This book" and "this page" mean the page open in the Reader: the
Reader tells Claude which page that is with every question.  Where a
question names a book, change it to one the dataset holds.
"""

QUESTIONS = {
    "About the dataset": [
        "What can I ask about this dataset?",
        "Which books and kinds of page does this file hold?",
        "What are the sections on a book page, and what does each one measure?",
        "What is a chapter page, and how does it differ from a book page?",
        "What is a Section page, and which parts of which books does this file have them for?",
        "What is a Compare page, and which pairs of books are compared here?",
        "What is a Word page, and which words have one in this file?",
        "What is a Testament page?",
        "Which version of Word Atlas made this run, and what was its build line?",
        "How many pages, tables and cells does this run hold?",
        "What does 'KJV' in the page titles mean for the figures?",
        "What is a Strong's number, and why do the tables show one after each word?",
        "What does 'roots' mean in the build line, and what is the gloss rule?",
        "Which tables in this file declined to measure something, and why?",
        "What does a footer line beginning 'Not measured' mean?",
        "Which questions can this dataset not answer that a reader might expect it to?",
    ],
    "Signature words (tables 1, 1a, 1b)": [
        "What are the top five signature words of this book, and what makes a word a signature word?",
        "What is keyness, and how is it calculated?",
        "Why does the signature table compare a Hebrew word with the Old Testament only and a Greek word with the New Testament only?",
        "Which signature words of this book are names, and what are the top three without them?",
        "What does the 'Concentration' footer of table 1 say for this book, and what does the percentage mean?",
        "Which words does this book use that are local, found in under a fifth of its chapters?",
        "What does 'spread' measure, and which signature words spread most evenly through this book?",
        "What does 'depth' measure, and in which chapter does each signature word go deepest?",
        "What are this book's 'local renderings', and what does that term mean?",
        "Which signature word of this book has the most English renderings, and what are they?",
        "What is table 1a, and what does it tell me about the Hebrew or Greek behind the words?",
        "What is table 1b, and what is this book's 'kind'?",
        "Which signature words are new in 1b, that is, key against the book's kind but not against the testament?",
        "Why does table 1b stop before 25 rows for some books?",
        "Compare the top ten signature words of two books in this file: what do they share?",
        "Which signature words of this book occur in fewer than three other books of its testament?",
        "What does 'rest/1000' mean beside 'Ezra/1000'?",
        "Which signature word has the highest count but the lowest keyness, and why?",
    ],
    "Function words and style (tables 1c, 7d)": [
        "What is table 1c, and what are function words?",
        "Which function words does this book use far more than its kind, and which far less?",
        "What is Burrows' Delta, in plain words?",
        "Which part of this book stands furthest from the rest of the book in its function words?",
        "What are the yardsticks in the 7d footer, and how do I read a Delta against them?",
        "What does 'nine in ten under' mean in the size yardstick?",
        "Does dropping the pronouns change which part of this book stands apart?",
        "What are the pairwise distances between the parts of this book in 7d?",
        "Why does the 7d note warn that a change of register can look like a change of author?",
        "Which part of this book is closest to the rest of the book in function words?",
        "Across every book in this file, which part has the largest Delta above its size yardstick?",
        "Which books in this file have a part whose Delta is above the nine-in-ten line for its size?",
        "What does the 'Delta against Rest' row mean when a book has two rests?",
        "How many tokens does each part of this book have, and does the smallest part look different only because it is small?",
        "Which function word contributes most to the distance between the two most different parts of this book?",
        "Do the Hebrew function words of this book behave like the Greek ones of a New Testament book?",
    ],
    "Vocabulary richness (table 1d)": [
        "What is table 1d, and what is vocabulary richness?",
        "Is this book richer or poorer in vocabulary than the other books of its kind?",
        "What is the 'run ceiling' in 1d, and why does it matter?",
        "Which book in this file has the richest vocabulary for its size, and which the poorest?",
        "Does this book's richness change between its parts?",
        "How does the richness of this book's chapters vary, and which chapter is the richest?",
        "What does the 1d footer say about where this book sits among its kind?",
    ],
    "The Septuagint (tables 1e, 1f, 4e, 4f)": [
        "What is the Septuagint, and why do the New Testament book pages have Septuagint tables?",
        "What is table 1e, and what does 'leaning' measure?",
        "Which words of this book lean most to the Septuagint rather than to the rest of the New Testament?",
        "What is table 1f, and what is this book's share of content words leaning to the Septuagint?",
        "Rank the New Testament books in this file by their Septuagint share in 1f.",
        "Which words of this book occur in the Septuagint and nowhere else in the New Testament?",
        "What is a 'Septuagint home', and which book of the Septuagint is home to most of this book's leaning words?",
        "What is table 4e, and what counts as a Septuagint echo in Greek?",
        "Which Septuagint echoes of this book are graded 'quotation', and what does the grade require?",
        "What does 'one word apart' mean in 4e?",
        "What is the 'content' column of 4e, and why does a quotation need three?",
        "Which echoes in 4e cross a one-word gap, and how is a gap bridged?",
        "What are the 'seams' in the 4e footer, and what do they say about the two taggings?",
        "Which Septuagint books are this book's echo partners in 4e?",
        "What is table 4f, and what does it mean for an English echo to be unconfirmed in Greek?",
        "Which echoes in 4f 'depart', and what does that say about the King James translators?",
        "What does 'formula' mean as a test result in 4f?",
        "What does 'no Greek verse mapped' mean, and which verses does it affect?",
        "Which quotation in this book comes from a Septuagint verse whose numbering differs from the English?",
        "Which echoes does Hebrews share with the Psalms in Greek, according to 4e?",
        "Across the New Testament books in this file, which Septuagint book is quoted most?",
    ],
    "Formulas and refrains (tables 2, 6b)": [
        "What is table 2, and what is a signature formula?",
        "What are the top formulas of this book, and how many verses hold each?",
        "How is a formula matched, by English words or by Strong's roots?",
        "Which formulas of this book are also found in other books, and which are its own?",
        "What is table 6b, and what is a refrain?",
        "Which refrains run through three or more chapters of this book?",
        "Which chapters share the most refrains with one another?",
        "What does 'by English' mean beside a formula in a two-language book such as Ezra or Daniel?",
        "Which formula of this book has the highest weight, and how is weight calculated?",
        "Is there a formula that appears in every chapter of this book?",
    ],
    "Neighbors (tables 3.1 to 3.5)": [
        "What are the neighbor tables, and what is a neighbor?",
        "What is the 'window' in the build line, and how does it shape the neighbor tables?",
        "Which words stand nearest to this book's leading word, and what is the pull between them?",
        "What does 'pull' measure between two words?",
        "Do the neighbors of 'lord' in this book differ from its neighbors in the rest of the Bible?",
        "Which neighbor of the leading word is itself a signature word of the book?",
        "Which of the five leading words has the most distinct neighbors?",
        "Which neighbor pairs in this book meet more than ten times?",
    ],
    "Echoes between books (tables 4, 4a, 4a2, 4b, 4c, 4d)": [
        "What is table 4, and what is an echo between books?",
        "Which books does this book echo most, by weight?",
        "What is table 4a, and what is an echo partner?",
        "Who reads whom: what does table 4a2 say about which book is the reader and which the read?",
        "What is the rarest echo this book shares with each partner?",
        "Which chapters of this book echo other books most, according to 4b?",
        "What is table 4c, the echo map, and how do I read its figures as text?",
        "What is table 4d, and which verses does this book share word for word with another?",
        "Which echoes of this book are with books of the other testament?",
        "Which echo in this book has the highest weight, and what are the two verses?",
        "Does this book echo its nearest partner evenly through its chapters, or in one place?",
        "Which books in this file echo each other most, taking every page together?",
        "Which echo partner of this book is surprising, a book one would not expect?",
        "How is echo weight calculated, and why does a rare word weigh more?",
        "Which chapter of this book has no echoes with other books at all?",
    ],
    "Reach and depth (table 5)": [
        "What is table 5, and what do reach and depth mean?",
        "Which of this book's signature words are both wide and deep, found in many chapters and strongly key in one?",
        "Which words are spread words, wide but shallow?",
        "Which words are local piles, deep in one chapter and absent elsewhere?",
        "Which chapter holds the deepest point of the most words?",
        "Does this book's reach and depth pattern suggest one voice throughout, or a book in parts?",
    ],
    "Within the book (tables 6, 6a, 6c, 6d)": [
        "What is table 6, and what is an echo within a book?",
        "Which two chapters of this book are closest to each other, according to 6a?",
        "What is each chapter's closest partner in the book, and are any chapters paired both ways?",
        "What is table 6c, and what are kin chapters?",
        "Which chapters share rare words in any order, and what are those words?",
        "What is table 6d, and what is shared vocabulary?",
        "Which chapters draw on the same uncommon words, and does that match the book's known structure?",
        "Which chapter of this book stands most alone, sharing least with the others?",
        "Do the chapter pairings in 6a line up with the parts in table 7?",
        "Which phrases does this book repeat across its chapters most often?",
    ],
    "Parts of a book (tables 7, 7a, 7b, 7c)": [
        "What is table 7, and what are the parts of this book?",
        "Where do the parts of this book come from, and can they be changed?",
        "What is table 7a, and which other books does each part of this book echo?",
        "Which part of this book has the most echoes with other books, and with which?",
        "What is table 7b, and how does it set section against section?",
        "Which two parts of this book are most alike, and which least?",
        "What is table 7c, and how do reach and depth differ by section?",
        "What is table 7.2, and why does this book have a second set of section tables?",
        "What are the parts of Ezra by language, and how does the Aramaic differ from the Hebrew in its figures?",
        "Which part of this book has the most signature words of its own?",
        "What is a cross-book section, such as the Succession Narrative or the prophetic cycles?",
        "What does the Section page for the Succession Narrative say about its distance from the rest of Samuel and Kings?",
        "Do the Elijah and Elisha cycles differ from the rest of Kings in their function words?",
        "What is the 'Rest of' row on a cross-book section page?",
    ],
    "Chapter pages": [
        "What does a chapter page hold that the book page does not?",
        "What are the leading words of this chapter, and how does 'leading' differ from 'signature'?",
        "Which formulas does this chapter hold, and which are shared with other chapters?",
        "What are this chapter's parallels, and which books do they come from?",
        "What is the synopsis table on a chapter page?",
        "Which chapter of this book has the most parallels in other books?",
        "Which chapter of this book is most like the chapter before it, and which breaks most sharply?",
        "What does the 'rest of the book' comparison on a chapter page measure?",
        "Which chapters of Revelation echo Ezekiel most, and in which verses?",
        "Which chapter of 1 Kings echoes 2 Chronicles most?",
    ],
    "Compare pages": [
        "What does a Compare page measure between two books?",
        "Which formulas do the two books of this Compare page share?",
        "Which refrains do the two books share, and in which chapters?",
        "Which signature words are common to both books, and which belong to one alone?",
        "What does 'by English' mean on a Compare page, and when does the atlas fall back to it?",
        "Of the pairs compared in this file, which two books are most alike?",
        "What does the Ezra and Nehemiah comparison say about whether they are one book or two?",
        "How do the two books of this Compare page differ in their function words?",
    ],
    "Testament pages": [
        "What is the Testament page, and what are 'home words'?",
        "Which books are home to the most words, that is, hold most of a word's occurrences?",
        "What is 'share' on the Testament page, and which word does this book hold the largest share of?",
        "Which words of this book are nearly its own, with most of their testament occurrences inside it?",
        "What is the home map, and how are its figures stored?",
    ],
    "Word pages": [
        "What is a Word page, and what does the shadow map show?",
        "Which books use the word of this Word page most per thousand words?",
        "In which chapter of this book is the word of the open Word page thickest?",
        "Which words have Word pages in this file, and why were they chosen?",
        "Does the word on this page occur in both testaments, and how does its rate differ?",
        "Which English spellings does the King James use for the root on this Word page?",
    ],
    "Kin and shared vocabulary": [
        "What is a Kin page?",
        "Which chapters across the Bible are kin to the chapter on this Kin page?",
        "Which rare words do the kin chapters share?",
        "Does the Kin page for Ezekiel 47 point to Revelation 22, and by which words?",
    ],
    "Across the whole file": [
        "Which book in this file has the most distinctive vocabulary against its testament?",
        "Which book has the most echoes with other books per thousand words?",
        "Which pair of books in this file are the closest echo partners?",
        "Which tables appear on every book page in this file, and which only on some?",
        "List every footer in this file that mentions 'register' or 'author'.",
        "Which books in this file have Aramaic in them, and how much?",
        "Which New Testament book in this file leans most on the Septuagint, and which least?",
        "Which part of any book in this file stands furthest from its rest, above its size yardstick?",
        "How many echoes in this file are graded 'quotation'?",
        "Which Septuagint book is the most common home for leaning words across all the New Testament books here?",
        "Which chapter in the whole file has the highest-keyness single word, and what is it?",
        "Which tables in this file have footers beginning 'Not measured', and what reasons do they give?",
        "Are there two runs in this file, and if so what changed between them?",
        "Summarise what this dataset says about Revelation in five sentences.",
        "Summarise what this dataset says about Ezra in five sentences.",
        "Summarise what this dataset says about 1 Kings in five sentences.",
    ],
    "Method and caution": [
        "What are the main cautions a reader should keep in mind when reading these tables?",
        "Why can a change of subject matter look like a change of author in the function-word tables?",
        "Why are the lower rows of a signature table for a small book called suggestions rather than findings?",
        "What is the difference between an echo found by root and one found by English wording?",
        "Why does the atlas compare a word with its own testament rather than with the whole Bible?",
        "What is a baseline group, and where does a book's group come from?",
        "What does it mean that two runs on the same build give the same text?",
        "Which figures in this file depend on the window size, and which do not?",
        "How would a different translation than the King James change these tables?",
        "What does the atlas do with a verse that has no Strong's tag?",
        "Which findings in this file would a sceptical reviewer question first, and why?",
        "What further tables or data would be needed to answer whether a part of a book had a different author?",
        "Which figures in this file are counts, which are rates, and which are statistics derived from them?",
        "If I wanted to check one figure by hand, which would be the easiest, and how?",
    ],
}


def all_questions():
    """Every question in order, as (group, question)."""
    return [(group, q) for group, qs in QUESTIONS.items() for q in qs]
